import { text, varchar, boolean, timestamp, json, int, mysqlTable } from "drizzle-orm/mysql-core";

export const templates = mysqlTable("templates", {
  id: varchar("id", { length: 24 }).primaryKey(),
  pages: json("pages").$type("object[]").default([]),
  masterinput: json("masterinput").$type("object[]").default([]),
  masterinputfromother: json("masterinputfromother").$type("object[]").default([]),
  importedInputSections: json("imported_input_sections").$type("object[]").default([]),
  pagesfromother: json("pagesfromother").$type("object[]").default([]),
  inputsections: json("inputsections").$type("object[]").default([]),
  dashboards: json("dashboards").$type("object[]").default([]),
  name: text("name"),
  subject: varchar("subject", { length: 512 }).default("No Subject"),
  scheme: text("scheme"),
  rulebook: text("rulebook"),
  description: text("description"),
  templateId: varchar("template_id", { length: 24 }),
  userid: varchar("userid", { length: 24 }),
  date: timestamp("date").defaultNow(),
  tags: json("tags").$type("string[]").default([]),
  favourites: json("favourites").$type("string[]").default([]),
  likedby: json("likedby").$type("string[]").default([]),
  adminusers: json("adminusers").$type("string[]").default([]),
  createdAt: timestamp("created_at").defaultNow(),
  quotes: json("quotes").default([]),
  currentversion: varchar("currentversion", { length: 24 }),
  publishid: varchar("publishid", { length: 24 }),
  toPublish: boolean("to_publish").default(false),
  blogdetails: json("blogdetails"),
  blocks: json("blocks"),
  linktohtml: text("linktohtml"),
  isDisabled: boolean("is_disabled").default(false),
  order: int("order").default(0),
});
